# Expose the web endpoints over HTTP
management.endpoints.web.exposure.include=health,prometheus

# Optional: Enable detailed health information (shows disk space, db status, etc.)
management.endpoint.health.show-details=always

management.endpoints.web.exposure.include=*
management.endpoint.prometheus.enabled=true
management.prometheus.metrics.export.enabled=true
