replicaCount: 2

image:
  repository: jayaramgopi143/springboot-app
  pullPolicy: IfNotPresent
  tag: "10"

resources:
  limits:
    cpu: "1"
    memory: 1024Mi
  requests:
    cpu: 500m
    memory: 512Mi

service:
  type: NodePort
  port: 80
  targetPort: 8080
  nodePort: 30081
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8080"
